version: "3.8"

x-egl-desktop: &egl-desktop
  runtime: sysbox-runc
  build:
    context: ./nvidia-egl-desktop
    target: kdeplasma
    #args:
      #KERNEL_VERSION: ${KERNEL_VERSION}
  networks:
    - desktop
  restart: unless-stopped
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
x-egl-desktop-labels: &egl-desktop-labels
  traefik.enable: true
x-egl-desktop-env: &egl-desktop-env
  TZ: ${HOST_TIMEZONE}
  WEBRTC_ENCODER: nvh264enc
  SIZEW: 1920
  SIZEH: 1080
  REFRESH: 60
  DPI: 96
  CDEPTH: 24
  TURN_HOST: ${HOST_LOCAL_IPV4}
  TURN_PORT: 3478
  TURN_PROTOCOL: udp
  TURN_TLS: true
  TURN_SHARED_SECRET: ${TURN_SECRET}

services:
  traefik:
    container_name: traefik
    image: traefik:v2.5
    network_mode: host
    command:
      --api.dashboard=false
      --providers.docker.endpoint=unix:///var/run/docker.sock
      --providers.docker.exposedbydefault=false
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
      --entrypoints.web.http.redirections.entryPoint.to=websecure
      --entrypoints.web.http.redirections.entryPoint.scheme=https
      --entrypoints.web.http.redirections.entrypoint.permanent=true
    cpuset: 20-23
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  coturn-server:
    container_name: coturn-server
    image: coturn/coturn:latest
    network_mode: host
    cpuset: 20-23
    expose:
      - 3478:3478/tcp
      - 3478:3478/udp
      - 49160-49200:49160-49200/udp
    command:
      -n
      -v
      --realm=localhost
      --fingerprint
      --listening-ip=0.0.0.0
      --listening-port=3478
      --external-ip=${HOST_LOCAL_IPV4}
      --relay-ip=${HOST_LOCAL_IPV4}
      --allow-loopback-peers
      --min-port=49160
      --max-port=49200
      --use-auth-secret
      --static-auth-secret='${TURN_SECRET}'
      --log-file=stdout
      --no-cli
    restart: unless-stopped

  desktop-development:
    <<: [ *egl-desktop ]
    container_name: desktop-development
    hostname: desktop-development
    labels:
      <<: [ *egl-desktop-labels ]
      description: Software Development
      traefik.http.routers.desktop-development.rule: Host(`desktop.development.${DOMAIN_NAME}`)
      traefik.http.services.desktop-development.loadbalancer.server.port: 8080
      traefik.http.routers.desktop-development.service: desktop-development
      traefik.http.routers.desktop-development.tls: true
      traefik.http.routers.desktop-development.entrypoints: websecure
    environment:
      <<: [ *egl-desktop-env ]
      PASSWD: ${DESKTOP_DEVELOPMENT_PASSWORD}
      BASIC_AUTH_PASSWORD: ${DESKTOP_DEVELOPMENT_PASSWORD}
    cpuset: 2-11
    ports:
      - 9090:8080/tcp
    volumes:
      - type: tmpfs
        target: /dev/shm:rw
      - /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw
      - /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw
      - /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw
      - /var/lib/lxcfs/proc/stat:/proc/stat:rw
      - /var/lib/lxcfs/proc/swaps:/proc/swaps:rw
      - /var/lib/lxcfs/proc/uptime:/proc/uptime:rw
      - /var/lib/lxcfs/sys/devices/system/cpu/online:/sys/devices/system/cpu/online:rw

  desktop-socials:
    <<: [ *egl-desktop ]
    container_name: desktop-socials
    hostname: desktop-socials
    labels:
      <<: [ *egl-desktop-labels ]
      description: Social Media accounts / Browsing
      traefik.http.routers.desktop-socials.rule: Host(`desktop.socials.${DOMAIN_NAME}`)
      traefik.http.services.desktop-socials.loadbalancer.server.port: 8080
      traefik.http.routers.desktop-socials.service: desktop-socials
      traefik.http.routers.desktop-socials.tls: true
      traefik.http.routers.desktop-socials.entrypoints: websecure
    environment:
      <<: [ *egl-desktop-env ]
      PASSWD: ${DESKTOP_SOCIALS_PASSWORD}
      BASIC_AUTH_PASSWORD: ${DESKTOP_SOCIALS_PASSWORD}
    cpuset: 12-15
    ports:
      - 9091:8080/tcp
    volumes:
      - type: tmpfs
        target: /dev/shm:rw
      - /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw
      - /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw
      - /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw
      - /var/lib/lxcfs/proc/stat:/proc/stat:rw
      - /var/lib/lxcfs/proc/swaps:/proc/swaps:rw
      - /var/lib/lxcfs/proc/uptime:/proc/uptime:rw
      - /var/lib/lxcfs/sys/devices/system/cpu/online:/sys/devices/system/cpu/online:rw

  desktop-finance:
    <<: [ *egl-desktop ]
    container_name: desktop-finance
    hostname: desktop-finance
    labels:
      <<: [ *egl-desktop-labels ]
      description: Banking, transactions, etc
      traefik.http.routers.desktop-finance.rule: Host(`desktop.finance.${DOMAIN_NAME}`)
      traefik.http.services.desktop-finance.loadbalancer.server.port: 8080
      traefik.http.routers.desktop-finance.service: desktop-finance
      traefik.http.routers.desktop-finance.tls: true
      traefik.http.routers.desktop-finance.entrypoints: websecure
    environment:
      <<: [ *egl-desktop-env ]
      PASSWD: ${DESKTOP_FINANCE_PASSWORD}
      BASIC_AUTH_PASSWORD: ${DESKTOP_FINANCE_PASSWORD}
    cpuset: 12-15
    ports:
      - 9092:8080/tcp
    volumes:
      - type: tmpfs
        target: /dev/shm:rw
      - /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw
      - /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw
      - /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw
      - /var/lib/lxcfs/proc/stat:/proc/stat:rw
      - /var/lib/lxcfs/proc/swaps:/proc/swaps:rw
      - /var/lib/lxcfs/proc/uptime:/proc/uptime:rw
      - /var/lib/lxcfs/sys/devices/system/cpu/online:/sys/devices/system/cpu/online:rw

  desktop-media:
    <<: [ *egl-desktop ]
    container_name: desktop-media
    hostname: desktop-media
    labels:
      <<: [ *egl-desktop-labels ]
      description: Torrenting / Mediacenter, Download and Play local media files
      traefik.http.routers.desktop-media.rule: Host(`desktop.media.${DOMAIN_NAME}`)
      traefik.http.services.desktop-media.loadbalancer.server.port: 8080
      traefik.http.routers.desktop-media.service: desktop-media
      traefik.http.routers.desktop-media.tls: true
      traefik.http.routers.desktop-media.entrypoints: websecure
    environment:
      <<: [ *egl-desktop-env ]
      PASSWD: ${DESKTOP_MEDIA_PASSWORD}
      BASIC_AUTH_PASSWORD: ${DESKTOP_MEDIA_PASSWORD}
    cpuset: 16-19
    ports:
      - 9093:8080/tcp
    volumes:
      - type: tmpfs
        target: /dev/shm:rw
      - /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw
      - /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw
      - /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw
      - /var/lib/lxcfs/proc/stat:/proc/stat:rw
      - /var/lib/lxcfs/proc/swaps:/proc/swaps:rw
      - /var/lib/lxcfs/proc/uptime:/proc/uptime:rw
      - /var/lib/lxcfs/sys/devices/system/cpu/online:/sys/devices/system/cpu/online:rw

networks:
  desktop:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
