services:
  coturn-server:
    profiles:
      - default
    container_name: coturn-server
    image: coturn/coturn:latest
    network_mode: host
    cpuset: 20-23
    expose:
      - 3478:3478/tcp
      - 3478:3478/udp
      - 49160-49200:49160-49200/udp
    command:
      -n
      -v
      --realm=localhost
      --fingerprint
      --listening-ip=0.0.0.0
      --listening-port=3478
      --external-ip=${HOST_LOCAL_IPV4}
      --relay-ip=${HOST_LOCAL_IPV4}
      --allow-loopback-peers
      --min-port=49160
      --max-port=49200
      --use-auth-secret
      --static-auth-secret='${TURN_SECRET}'
      --log-file=stdout
      --no-cli
    restart: unless-stopped

